/***********************************************************************/
/*                                                                     */
/*  FILE        :Empty.c                                               */
/*  DATE        :Mon, Jan 08, 2007                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :Other                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.0).     */
/*                                                                     */
/***********************************************************************/
     
#include "qsk_bsp.h"
#include "task.h"
#include "app.h"

// prototypes

void mcu_init(void);	              

/* *******************************************************************
 Description:
 Entry:
 Returns:
 
 Notes:
 
***********************************************************************/ 


void main(void)
{	
	INT16U *stk;
	mcu_init();
	lcd_init();
	led_init();
	switch_init();
	app_init();
	init_stack_arr();
	list_init();
	SAVE_ISP(stk)
	cpp(stk);
		
	Task_create(&deviceDriver, 100, stk);
	
	sched_init();
}
